
# Use 14.04 because 12.04's wget (or curl) doesn't seem to work
dist: trusty
sudo: true

language: generic

env:
  global:
    - PACKER_LOG=1
    - PACKER_VERSION='0.12.2'
    - PACKER_CACHE_DIR="${HOME}/.cache"

install:
  - mkdir -p "${HOME}/.local/bin"
  - wget --no-check-certificate "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
  - unzip packer_${PACKER_VERSION}_linux_amd64.zip -d "${HOME}/.local/bin"
  - which packer

script:
  - packer validate archlinux.json
  # - packer build archlinux.json

addons:
  apt:
    packages:
      - linux-headers-3.13.0-100-generic # Specific to 14.04 (uname -r)
      - linux-headers-4.4.0-45-generic # Needed for the docker container worker.
      - linux-headers-4.4.0-51-generic # Also needed for the fully-virtualised worker.
      - linux-headers-generic
      - unzip
      - virtualbox
      - virtualbox-dkms
      - virtualbox-guest-additions-iso
      - virtualbox-guest-utils
      - virtualbox-guest-x11
      - virtualbox-qt # Needed in case we need to launch a GUI for whatever reason.
      - wget
