
env:
  global:
    - PACKER_VERSION=0.12.2

install:
  - wget --no-check-certificate https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
  - unzip packer_${PACKER_VERSION}_linux_amd64.zip

script:
  - packer build archlinux.json

addons:
  apt:
    packages:
      - unzip
      - virtualbox
      - virtualbox-guest-additions
      - virtualbox-guest-additions-iso
