version: 1.0.{build}

cache:
  - packer_cache
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib

install:
  - git submodule update --init --recursive
  - cinst packer
  - cinst virtualbox
  - refreshenv
  - set

build_script:
  - set PACKER_CACHE_DIR=%cd%\packer_cache
  - packer build archlinux.json