version: 1.0.{build}

cache:
  - packer_cache
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib

install:
  - cinst: packer
  - cinst: vagrant
  - cinst: virtualbox

build_script:
  - packer build archlinux.json