version: 1.0.{build}

cache:
  - packer_cache
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib

init:
  # Display RDP info in case we need to debug the build
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # Disable Hyper-V (enable detection of 64-bit guests)
  - ps: Remove-WindowsFeature -Name Hyper-V

install:
  - git submodule update --init --recursive
  - cinst packer
  - cinst virtualbox
  - refreshenv
  - set

build_script:
  - set PACKER_CACHE_DIR=%cd%\packer_cache
  # Use 32-bit because AppVeyor doesn't (yet) support 64-bit guests.
  - packer build archlinux.json
