version: 1.0.{build}

cache:
  - packer_cache
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib

# Display RDP info in case we need to debug the build
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - git submodule update --init --recursive
  - cinst packer
  - cinst virtualbox
  - refreshenv
  - set

build_script:
  - set PACKER_CACHE_DIR=%cd%\packer_cache
  - packer build -var arch=32 archlinux.json
