# This doesn't work, purely for the reason that AppVeyor doesn't support 64-bit guests.

version: 1.0.{build}

# Guarantees that we are using Windows Server 2016,
# which (apparently) offers nested 64-bit virtualisation.
image: Visual Studio 2017

cache:
  - packer_cache
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib

init:
  # Display RDP info in case we need to debug the build
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - git submodule update --init --recursive
  - cinst packer
  - cinst virtualbox
  - refreshenv
  - set

build_script:
  - set PACKER_LOG=1
  - set PACKER_CACHE_DIR=%cd%\packer_cache
  - packer validate archlinux.json
  # Check if we have VT-X enabled
  - ps: systeminfo | Select-String -Pattern "Hyper-V Requirements"
  # We don't try to build since we get the following error in VirtualBox:
  # VT-X/AMD-V hardware acceleration is not available on your system.
  # Your 64-bit guest will fail to detect a 64-bit CPU and will not be able to boot.
  # - packer build archlinux.json
