---
- hosts: localhost
  # Note that these must also be passed into the `role_paths` filed in archlinux.json.
  # We use this instead of "playbook_dir": "ansible", since `ansible` is a git repository,
  # and uploading the entirety of its contents wreaks havoc with the git module
  # since `git ls-remote` does not work as intended when its cwd is inside a git repository.
  roles:
    - aura
    - autologin
    - bspwm
    - chromium
    - c++_development
    - development
    - desktop
    - docker
    - dotfiles
    - haskell_development
    - java_development
    - javascript_development
    - python_development
    - retroarch
    - snapper
    - system
    - user
    - vagrant
    - vim_plugins
    - virtualbox
    - xorg
  become: yes
  vars:
    system_hostname: porygon
